# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_pages\İsciEkle.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_isciEkleWindow(object):
    def setupUi(self, isciEkleWindow):
        isciEkleWindow.setObjectName("isciEkleWindow")
        isciEkleWindow.resize(657, 413)
        isciEkleWindow.setStyleSheet("")
        self.ana_widget = QtWidgets.QWidget(isciEkleWindow)
        self.ana_widget.setObjectName("ana_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.ana_widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        isciEkleWindow.setCentralWidget(self.ana_widget)
        self.menubar = QtWidgets.QMenuBar(isciEkleWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 657, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        isciEkleWindow.setMenuBar(self.menubar)
        self.actionStart_Camera = QtWidgets.QAction(isciEkleWindow)
        self.actionStart_Camera.setObjectName("actionStart_Camera")
        self.actionStop_Camera = QtWidgets.QAction(isciEkleWindow)
        self.actionStop_Camera.setObjectName("actionStop_Camera")
        self.actionExit = QtWidgets.QAction(isciEkleWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionStart_Camera)
        self.menuMenu.addAction(self.actionStop_Camera)
        self.menuExit.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(isciEkleWindow)
        QtCore.QMetaObject.connectSlotsByName(isciEkleWindow)

    def retranslateUi(self, isciEkleWindow):
        _translate = QtCore.QCoreApplication.translate
        isciEkleWindow.setWindowTitle(_translate("isciEkleWindow", "MainWindow"))
        self.menuMenu.setTitle(_translate("isciEkleWindow", "Menu"))
        self.menuExit.setTitle(_translate("isciEkleWindow", "Exit"))
        self.actionStart_Camera.setText(_translate("isciEkleWindow", "Start Camera"))
        self.actionStop_Camera.setText(_translate("isciEkleWindow", "Stop Camera"))
        self.actionExit.setText(_translate("isciEkleWindow", "Exit"))
