# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_pages\supervisor_Ekle.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_SuperVisorWindow(object):
    def setupUi(self, add_SuperVisorWindow):
        add_SuperVisorWindow.setObjectName("add_SuperVisorWindow")
        add_SuperVisorWindow.resize(537, 821)
        add_SuperVisorWindow.setMinimumSize(QtCore.QSize(537, 821))
        add_SuperVisorWindow.setMaximumSize(QtCore.QSize(537, 821))
        add_SuperVisorWindow.setStyleSheet("")
        self.ana_widget = QtWidgets.QWidget(add_SuperVisorWindow)
        self.ana_widget.setObjectName("ana_widget")
        self._2 = QtWidgets.QGridLayout(self.ana_widget)
        self._2.setContentsMargins(0, 0, 0, 0)
        self._2.setSpacing(0)
        self._2.setObjectName("_2")
        self.frame = QtWidgets.QFrame(self.ana_widget)
        self.frame.setStyleSheet("QFrame{\n"
"background: #354152;\n"
"}\n"
"\n"
"QLabel{\n"
"    font-size:24px;\n"
"    color:white;\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"border-radius:10px;\n"
"padding-left: 15px;\n"
"font-size:16px;\n"
"\n"
"}\n"
"QPushButton{\n"
"height:32px;\n"
"border-radius: 15px;\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:0.466409, x2:0.188, y2:0.482727, stop:0.823864 rgba(82, 185, 143, 255), stop:1 rgba(115, 185, 153, 255));\n"
"padding: 8px 16px;\n"
"color: white;\n"
"font-size: 20px;\n"
"}\n"
"QPushButton:pressed{\n"
"color: black;\n"
"background: #008bd1\n"
"}\n"
"\n"
"\n"
"QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    font-size:16px;\n"
"    padding-left:15px;\n"
"\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: white;\n"
"    border: 1px solid gray;\n"
"    box-shadow: transparent;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-color: transparent;\n"
"}\n"
"\n"
"\n"
"\n"
"QSpinBox{\n"
"height:42px;\n"
"}\n"
"\n"
"QSpinBox {\n"
"    /*text-align: center;*/\n"
"    padding-right: 15px;\n"
"    border-width: 5px;\n"
"    border-radius:10px;\n"
"    padding-left:15px;\n"
"    font-size:20px;\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"     subcontrol-origin: border;\n"
"     padding-left: 10px;\n"
"     padding-right: 40px;\n"
"     width: 16px; /* 16 + 2*1px border-width = 15px padding + 3px parent border */\n"
"     /*height: 14px;*/\n"
"     border-width: 1px;\n"
"     border-radius: 5px;\n"
"     background-color: #eeeeee;\n"
"\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    subcontrol-position: top right; /* position at the top right corner */\n"
"    height:42px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover, QSpinBox::down-button:hover {\n"
"    background-color: #bbbb;\n"
"}\n"
"\n"
"QSpinBox::up-arrow:disabled, QSpinBox::down-arrow:disabled {\n"
"    image: none;\n"
"}\n"
"QSpinBox::up-arrow, QSpinBox::down-arrow {\n"
"     width: 20px;\n"
"     height: 20px;\n"
"     border: 1px;\n"
"}\n"
"QSpinBox::up-arrow {\n"
"padding-left:20px;\n"
"    image: url(:/resimler/icons/chevron-up.png);\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    subcontrol-position: bottom left; /* position at bottom right corner */\n"
"    height:42px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"image: url(:/resimler/icons/chevron-down.png);\n"
"padding-left:20px;\n"
"}\n"
"\n"
"QGroupBox{\n"
"border: none;\n"
"}\n"
"\n"
"QToolButton{\n"
"margin-left:10px;\n"
"height:42px;\n"
"width:500px;\n"
" border-width: 1px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setStyleSheet("QLineEdit{\n"
"height:42px;\n"
"}\n"
"QComboBox{\n"
"height:42px;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.txt_Email = QtWidgets.QLineEdit(self.groupBox)
        self.txt_Email.setText("")
        self.txt_Email.setMaxLength(50)
        self.txt_Email.setObjectName("txt_Email")
        self.gridLayout_2.addWidget(self.txt_Email, 4, 2, 1, 1)
        self.btn_kayit = QtWidgets.QPushButton(self.groupBox)
        self.btn_kayit.setObjectName("btn_kayit")
        self.gridLayout_2.addWidget(self.btn_kayit, 8, 0, 1, 3)
        self.txt_AdiSoyadi = QtWidgets.QLineEdit(self.groupBox)
        self.txt_AdiSoyadi.setText("")
        self.txt_AdiSoyadi.setMaxLength(100)
        self.txt_AdiSoyadi.setObjectName("txt_AdiSoyadi")
        self.gridLayout_2.addWidget(self.txt_AdiSoyadi, 3, 2, 1, 1)
        self.txt_Username = QtWidgets.QLineEdit(self.groupBox)
        self.txt_Username.setText("")
        self.txt_Username.setMaxLength(20)
        self.txt_Username.setObjectName("txt_Username")
        self.gridLayout_2.addWidget(self.txt_Username, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.txt_Password = QtWidgets.QLineEdit(self.groupBox)
        self.txt_Password.setMaxLength(20)
        self.txt_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_Password.setObjectName("txt_Password")
        self.gridLayout_2.addWidget(self.txt_Password, 5, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.btn_resimCek = QtWidgets.QToolButton(self.frame)
        self.btn_resimCek.setObjectName("btn_resimCek")
        self.gridLayout_3.addWidget(self.btn_resimCek, 2, 0, 1, 1)
        self._2.addWidget(self.frame, 0, 0, 1, 1)
        add_SuperVisorWindow.setCentralWidget(self.ana_widget)
        self.menubar = QtWidgets.QMenuBar(add_SuperVisorWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 537, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        add_SuperVisorWindow.setMenuBar(self.menubar)
        self.actionStart_Camera = QtWidgets.QAction(add_SuperVisorWindow)
        self.actionStart_Camera.setObjectName("actionStart_Camera")
        self.actionStop_Camera = QtWidgets.QAction(add_SuperVisorWindow)
        self.actionStop_Camera.setObjectName("actionStop_Camera")
        self.actionExit = QtWidgets.QAction(add_SuperVisorWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionStart_Camera)
        self.menuMenu.addAction(self.actionStop_Camera)
        self.menuExit.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(add_SuperVisorWindow)
        QtCore.QMetaObject.connectSlotsByName(add_SuperVisorWindow)
        add_SuperVisorWindow.setTabOrder(self.txt_Username, self.txt_AdiSoyadi)
        add_SuperVisorWindow.setTabOrder(self.txt_AdiSoyadi, self.txt_Email)
        add_SuperVisorWindow.setTabOrder(self.txt_Email, self.btn_kayit)

    def retranslateUi(self, add_SuperVisorWindow):
        _translate = QtCore.QCoreApplication.translate
        add_SuperVisorWindow.setWindowTitle(_translate("add_SuperVisorWindow", "MainWindow"))
        self.label.setText(_translate("add_SuperVisorWindow", "KAMERA EKRANI"))
        self.label_10.setText(_translate("add_SuperVisorWindow", "Şifre"))
        self.label_5.setText(_translate("add_SuperVisorWindow", "Email"))
        self.txt_Email.setPlaceholderText(_translate("add_SuperVisorWindow", "Email"))
        self.btn_kayit.setText(_translate("add_SuperVisorWindow", "Supervisor Ekle"))
        self.txt_AdiSoyadi.setPlaceholderText(_translate("add_SuperVisorWindow", "Adı Soyadı"))
        self.txt_Username.setPlaceholderText(_translate("add_SuperVisorWindow", "Username"))
        self.label_2.setText(_translate("add_SuperVisorWindow", "Kullanıcı Adı"))
        self.label_3.setText(_translate("add_SuperVisorWindow", "Adı Soyadı"))
        self.txt_Password.setPlaceholderText(_translate("add_SuperVisorWindow", "Şifre"))
        self.btn_resimCek.setText(_translate("add_SuperVisorWindow", "Resim Çek"))
        self.menuMenu.setTitle(_translate("add_SuperVisorWindow", "Menu"))
        self.menuExit.setTitle(_translate("add_SuperVisorWindow", "Exit"))
        self.actionStart_Camera.setText(_translate("add_SuperVisorWindow", "Start Camera"))
        self.actionStop_Camera.setText(_translate("add_SuperVisorWindow", "Stop Camera"))
        self.actionExit.setText(_translate("add_SuperVisorWindow", "Exit"))
