# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_pages\isciyi_vardiyaya_ekle.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VardiyaIsciEkleForm(object):
    def setupUi(self, VardiyaIsciEkleForm):
        VardiyaIsciEkleForm.setObjectName("VardiyaIsciEkleForm")
        VardiyaIsciEkleForm.resize(588, 516)
        self.gridLayout = QtWidgets.QGridLayout(VardiyaIsciEkleForm)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(VardiyaIsciEkleForm)
        self.frame.setStyleSheet("QFrame{\n"
"\n"
"background: #354152;\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 2px solid gray;\n"
"    border-color:white;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    font-size:20px;\n"
"    padding-left:15px;\n"
"    height:42px;\n"
"    border-radius:15px;\n"
"    border-color: #303030;\n"
"    background: transparent;\n"
"    color:#ffffffff;\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    font-size:20px;\n"
"    border-color: rgb(255, 255, 255);\n"
"    padding-left:15px;\n"
"    height:42px;\n"
"    border-radius:15px;\n"
"    border-color: #303030;\n"
"    background: transparent;\n"
"    color:white;\n"
"\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: #354152;\n"
"    border: 1px solid gray;\n"
"    color:white;\n"
"\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-color: white;\n"
"}\n"
"QPushButton{\n"
"border-radius: 15px;\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:0.466409, x2:0.188, y2:0.482727, stop:0.823864 rgba(82, 185, 143, 255), stop:1 rgba(115, 185, 153, 255));\n"
"padding: 8px 16px;\n"
"color: white;\n"
"font-size: 20px;\n"
"height:42px;\n"
"}\n"
"QPushButton:pressed{\n"
"color: black;\n"
"background: #008bd1\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.txt_KimlikNo = QtWidgets.QLineEdit(self.frame)
        self.txt_KimlikNo.setGeometry(QtCore.QRect(300, 30, 261, 46))
        self.txt_KimlikNo.setMaxLength(11)
        self.txt_KimlikNo.setObjectName("txt_KimlikNo")
        self.txt_AdSoyad = QtWidgets.QLineEdit(self.frame)
        self.txt_AdSoyad.setEnabled(False)
        self.txt_AdSoyad.setGeometry(QtCore.QRect(300, 110, 261, 46))
        self.txt_AdSoyad.setObjectName("txt_AdSoyad")
        self.txt_Vardiya = QtWidgets.QLineEdit(self.frame)
        self.txt_Vardiya.setEnabled(False)
        self.txt_Vardiya.setGeometry(QtCore.QRect(300, 190, 261, 46))
        self.txt_Vardiya.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.txt_Vardiya.setObjectName("txt_Vardiya")
        self.btn_ara = QtWidgets.QPushButton(self.frame)
        self.btn_ara.setGeometry(QtCore.QRect(310, 260, 241, 41))
        self.btn_ara.setStyleSheet("")
        self.btn_ara.setObjectName("btn_ara")
        self.cmb_Vardiyalar = QtWidgets.QComboBox(self.frame)
        self.cmb_Vardiyalar.setGeometry(QtCore.QRect(12, 350, 541, 46))
        self.cmb_Vardiyalar.setObjectName("cmb_Vardiyalar")
        self.btn_Ekle = QtWidgets.QPushButton(self.frame)
        self.btn_Ekle.setGeometry(QtCore.QRect(12, 437, 541, 41))
        self.btn_Ekle.setStyleSheet("")
        self.btn_Ekle.setObjectName("btn_Ekle")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 272, 292))
        self.label.setStyleSheet("background:white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(VardiyaIsciEkleForm)
        QtCore.QMetaObject.connectSlotsByName(VardiyaIsciEkleForm)

    def retranslateUi(self, VardiyaIsciEkleForm):
        _translate = QtCore.QCoreApplication.translate
        VardiyaIsciEkleForm.setWindowTitle(_translate("VardiyaIsciEkleForm", "Form"))
        self.txt_KimlikNo.setPlaceholderText(_translate("VardiyaIsciEkleForm", "Tc No"))
        self.txt_AdSoyad.setPlaceholderText(_translate("VardiyaIsciEkleForm", "Adı ve Soyadı"))
        self.txt_Vardiya.setPlaceholderText(_translate("VardiyaIsciEkleForm", "Vardiya"))
        self.btn_ara.setText(_translate("VardiyaIsciEkleForm", "Ara"))
        self.btn_Ekle.setText(_translate("VardiyaIsciEkleForm", "İşçiyi Vardiyaya Ekle"))
        self.label.setText(_translate("VardiyaIsciEkleForm", "TextLabel"))
