# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_pages\isci_duzenle.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IsciDuzenleForm(object):
    def setupUi(self, IsciDuzenleForm):
        IsciDuzenleForm.setObjectName("IsciDuzenleForm")
        IsciDuzenleForm.resize(618, 619)
        self.gridLayout = QtWidgets.QGridLayout(IsciDuzenleForm)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(IsciDuzenleForm)
        self.frame.setStyleSheet("QFrame{\n"
"background: #354152;\n"
"}\n"
"\n"
"\n"
"\n"
"QLineEdit{\n"
"height: 45px;\n"
"border-radius:15px;\n"
"padding-left: 18px;\n"
"font-size: 20px;\n"
"background:white;\n"
"}\n"
"QPushButton{\n"
"height:32px;\n"
"border-radius: 15px;\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:0.466409, x2:0.188, y2:0.482727, stop:0.823864 rgba(82, 185, 143, 255), stop:1 rgba(115, 185, 153, 255));\n"
"padding: 8px 16px;\n"
"color: white;\n"
"font-size: 20px;\n"
"}\n"
"QPushButton:pressed{\n"
"color: black;\n"
"background: #008bd1\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ogrenci_update = QtWidgets.QPushButton(self.frame)
        self.ogrenci_update.setGeometry(QtCore.QRect(30, 540, 521, 51))
        self.ogrenci_update.setObjectName("ogrenci_update")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(230, 20, 331, 521))
        self.frame_2.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    min-width: 6em;\n"
"    font-size:16px;\n"
"    padding-left:15px;\n"
"    height:42px;\n"
"\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background: white;\n"
"    border: 1px solid gray;\n"
"    box-shadow: transparent;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-color: transparent;\n"
"}\n"
"\n"
"QFrame{\n"
"border:none;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ogrenci_soyadi = QtWidgets.QLineEdit(self.frame_2)
        self.ogrenci_soyadi.setObjectName("ogrenci_soyadi")
        self.gridLayout_2.addWidget(self.ogrenci_soyadi, 2, 0, 1, 2)
        self.ogrenci_vardiyaNo = QtWidgets.QLineEdit(self.frame_2)
        self.ogrenci_vardiyaNo.setEnabled(False)
        self.ogrenci_vardiyaNo.setObjectName("ogrenci_vardiyaNo")
        self.gridLayout_2.addWidget(self.ogrenci_vardiyaNo, 0, 0, 1, 2)
        self.ogrenci_adi = QtWidgets.QLineEdit(self.frame_2)
        self.ogrenci_adi.setObjectName("ogrenci_adi")
        self.gridLayout_2.addWidget(self.ogrenci_adi, 1, 0, 1, 2)
        self.cmb_Vardiya = QtWidgets.QComboBox(self.frame_2)
        self.cmb_Vardiya.setObjectName("cmb_Vardiya")
        self.gridLayout_2.addWidget(self.cmb_Vardiya, 3, 1, 1, 1)
        self.txt_bolum = QtWidgets.QLineEdit(self.frame_2)
        self.txt_bolum.setEnabled(False)
        self.txt_bolum.setStyleSheet("font-size:12px;")
        self.txt_bolum.setObjectName("txt_bolum")
        self.gridLayout_2.addWidget(self.txt_bolum, 3, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(20, 20, 201, 461))
        self.frame_3.setStyleSheet("QFrame{\n"
"border:none;\n"
"}\n"
"\n"
"QLabel{\n"
"    height:200px;\n"
"}\n"
"\n"
"QPushButton{\n"
"height:42px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.resimYukle = QtWidgets.QPushButton(self.frame_3)
        self.resimYukle.setGeometry(QtCore.QRect(0, 220, 201, 41))
        self.resimYukle.setObjectName("resimYukle")
        self.ogrenci_resim = QtWidgets.QLabel(self.frame_3)
        self.ogrenci_resim.setGeometry(QtCore.QRect(0, 10, 200, 190))
        self.ogrenci_resim.setStyleSheet("background: white;\n"
"")
        self.ogrenci_resim.setAlignment(QtCore.Qt.AlignCenter)
        self.ogrenci_resim.setObjectName("ogrenci_resim")
        self.ogrenci_aldigiDersler = QtWidgets.QListWidget(self.frame_3)
        self.ogrenci_aldigiDersler.setGeometry(QtCore.QRect(0, 280, 201, 171))
        self.ogrenci_aldigiDersler.setStyleSheet("background: white;")
        self.ogrenci_aldigiDersler.setObjectName("ogrenci_aldigiDersler")
        self.btn_vardiyayCikart = QtWidgets.QPushButton(self.frame)
        self.btn_vardiyayCikart.setGeometry(QtCore.QRect(20, 480, 201, 41))
        self.btn_vardiyayCikart.setObjectName("btn_vardiyayCikart")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(IsciDuzenleForm)
        QtCore.QMetaObject.connectSlotsByName(IsciDuzenleForm)

    def retranslateUi(self, IsciDuzenleForm):
        _translate = QtCore.QCoreApplication.translate
        IsciDuzenleForm.setWindowTitle(_translate("IsciDuzenleForm", "Form"))
        self.ogrenci_update.setText(_translate("IsciDuzenleForm", "Güncelle"))
        self.ogrenci_soyadi.setPlaceholderText(_translate("IsciDuzenleForm", "Soyadı"))
        self.ogrenci_vardiyaNo.setPlaceholderText(_translate("IsciDuzenleForm", "İşçi No"))
        self.ogrenci_adi.setPlaceholderText(_translate("IsciDuzenleForm", "Adı"))
        self.txt_bolum.setPlaceholderText(_translate("IsciDuzenleForm", "Vardiya"))
        self.resimYukle.setText(_translate("IsciDuzenleForm", "Yeni Resim Çek"))
        self.ogrenci_resim.setText(_translate("IsciDuzenleForm", "Resim"))
        self.btn_vardiyayCikart.setText(_translate("IsciDuzenleForm", "Vardiyayı Çıkart"))
