# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_pages\kayit.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtWidgets

from ui_pages.resoruces_rc import *


class Ui_VardiyaSorumluKayit(object):
    def setupUi(self, VardiyaSorumluKayit):
        VardiyaSorumluKayit.setObjectName("VardiyaSorumluKayit")
        VardiyaSorumluKayit.setWindowModality(QtCore.Qt.NonModal)
        VardiyaSorumluKayit.resize(423, 740)
        VardiyaSorumluKayit.setMouseTracking(False)
        VardiyaSorumluKayit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        VardiyaSorumluKayit.setWindowTitle("Form")
        VardiyaSorumluKayit.setToolTipDuration(0)
        VardiyaSorumluKayit.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(VardiyaSorumluKayit)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(VardiyaSorumluKayit)
        self.frame.setMouseTracking(True)
        self.frame.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frame.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.frame.setAcceptDrops(False)
        self.frame.setToolTipDuration(0)
        self.frame.setStyleSheet("QFrame{\n"
                                 "\n"
                                 "background: #354152;\n"
                                 "\n"
                                 "}\n"
                                 "\n"
                                 "QLineEdit{\n"
                                 "    border: 1px solid gray;\n"
                                 "    border-radius: 10px;\n"
                                 "    min-width: 6em;\n"
                                 "    font-size:20px;\n"
                                 "    padding-left:15px;\n"
                                 "    height:42px;\n"
                                 "    border-radius:15px;\n"
                                 "    border-color: #303030;\n"
                                 "    background: transparent;\n"
                                 "    color:white;\n"
                                 "\n"
                                 "\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "\n"
                                 "QComboBox {\n"
                                 "    border: 1px solid gray;\n"
                                 "    border-radius: 10px;\n"
                                 "    min-width: 6em;\n"
                                 "    font-size:20px;\n"
                                 "    padding-left:15px;\n"
                                 "    height:42px;\n"
                                 "    border-radius:15px;\n"
                                 "    border-color: #303030;\n"
                                 "    background: transparent;\n"
                                 "    color:white;\n"
                                 "\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox:on {\n"
                                 "    border-bottom-left-radius: 0px;\n"
                                 "    border-bottom-right-radius: 0px;\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox QAbstractItemView {\n"
                                 "    border-bottom-right-radius: 10px;\n"
                                 "    border-bottom-left-radius: 10px;\n"
                                 "    background: #354152;\n"
                                 "    border: 1px solid gray;\n"
                                 "    color:white;\n"
                                 "\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox::drop-down {\n"
                                 "    border-color: white;\n"
                                 "}\n"
                                 "QPushButton{\n"
                                 "border-radius: 15px;\n"
                                 "background-color: qlineargradient(spread:reflect, x1:1, y1:0.466409, x2:0.188, y2:0.482727, stop:0.823864 rgba(82, 185, 143, 255), stop:1 rgba(115, 185, 153, 255));\n"
                                 "padding: 8px 16px;\n"
                                 "color: white;\n"
                                 "font-size: 20px;\n"
                                 "height:42px;\n"
                                 "}\n"
                                 "QPushButton:pressed{\n"
                                 "color: black;\n"
                                 "background: #008bd1\n"
                                 "\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 240, 371, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_signup = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_signup.setStyleSheet("")
        self.btn_signup.setObjectName("btn_signup")
        self.gridLayout_2.addWidget(self.btn_signup, 6, 0, 1, 2)
        self.txt_mail = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_mail.setStyleSheet("")
        self.txt_mail.setText("")
        self.txt_mail.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.txt_mail.setObjectName("txt_mail")
        self.gridLayout_2.addWidget(self.txt_mail, 5, 0, 1, 2)
        self.txt_soyadi = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_soyadi.setText("")
        self.txt_soyadi.setObjectName("txt_soyadi")
        self.gridLayout_2.addWidget(self.txt_soyadi, 0, 1, 1, 1)
        self.txt_sifre = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_sifre.setText("")
        self.txt_sifre.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.txt_sifre.setObjectName("txt_sifre")
        self.gridLayout_2.addWidget(self.txt_sifre, 3, 0, 1, 2)
        self.txt_kullaniciAdi = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_kullaniciAdi.setText("")
        self.txt_kullaniciAdi.setObjectName("txt_kullaniciAdi")
        self.gridLayout_2.addWidget(self.txt_kullaniciAdi, 2, 0, 1, 2)
        self.txt_adi = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_adi.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_adi.setText("")
        self.txt_adi.setObjectName("txt_adi")
        self.gridLayout_2.addWidget(self.txt_adi, 0, 0, 1, 1)
        self.txt_sifreTekrar = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_sifreTekrar.setText("")
        self.txt_sifreTekrar.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.txt_sifreTekrar.setObjectName("txt_sifreTekrar")
        self.gridLayout_2.addWidget(self.txt_sifreTekrar, 4, 0, 1, 2)
        self.cmb_vardiya = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cmb_vardiya.setObjectName("cmb_vardiya")
        self.cmb_vardiya.addItem("")
        self.cmb_vardiya.addItem("")
        self.cmb_vardiya.addItem("")
        self.gridLayout_2.addWidget(self.cmb_vardiya, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 30, 369, 142))
        self.label.setStyleSheet("image: url(:/resimler/icons/damla.png);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 180, 369, 69))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color: #7E8BA3;\n"
                                   "font: 44px \"Helvetica Neue\", sans-serif;\n"
                                   "margin: 0px 0px 16px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(VardiyaSorumluKayit)
        QtCore.QMetaObject.connectSlotsByName(VardiyaSorumluKayit)
        VardiyaSorumluKayit.setTabOrder(self.txt_adi, self.txt_soyadi)
        VardiyaSorumluKayit.setTabOrder(self.txt_soyadi, self.txt_kullaniciAdi)
        VardiyaSorumluKayit.setTabOrder(self.txt_kullaniciAdi, self.txt_sifre)
        VardiyaSorumluKayit.setTabOrder(self.txt_sifre, self.txt_sifreTekrar)
        VardiyaSorumluKayit.setTabOrder(self.txt_sifreTekrar, self.txt_mail)
        VardiyaSorumluKayit.setTabOrder(self.txt_mail, self.btn_signup)

    def retranslateUi(self, VardiyaSorumluKayit):
        _translate = QtCore.QCoreApplication.translate
        self.btn_signup.setText(_translate("VardiyaSorumluKayit", "KAYIT OL"))
        self.txt_mail.setPlaceholderText(_translate("VardiyaSorumluKayit", "info@mailadress.com"))
        self.txt_soyadi.setPlaceholderText(_translate("VardiyaSorumluKayit", "Soyadı"))
        self.txt_sifre.setPlaceholderText(_translate("VardiyaSorumluKayit", "Şifre"))
        self.txt_kullaniciAdi.setPlaceholderText(_translate("VardiyaSorumluKayit", "Kullanıcı Adı"))
        self.txt_adi.setPlaceholderText(_translate("VardiyaSorumluKayit", "Adı"))
        self.txt_sifreTekrar.setPlaceholderText(_translate("VardiyaSorumluKayit", "Tekrar Şifre"))
        self.cmb_vardiya.setItemText(0, _translate("VardiyaSorumluKayit", "Rol Seçiniz"))
        self.cmb_vardiya.setItemText(1, _translate("VardiyaSorumluKayit", "Admin"))
        self.cmb_vardiya.setItemText(2, _translate("VardiyaSorumluKayit", "Vardiya Sorumlusu"))
        self.label_2.setText(_translate("VardiyaSorumluKayit", "KAYIT OL"))
